Ndim_ := 4:
x1_ := t:
x2_ := x:
x3_ := y:
x4_ := z:
sig_ := 2:
complex_ := {}:
g11_ := -x^(2*m):
g22_ := x^(2*m):
g33_ := x^(2*m):
g44_ := x^(2*m):
constraint_ := [ ]:
Info_ := `Beckers & Sinzinkayo & Demaret, parameter d set to 0`:
Ref_ := ["Beckers & Sinzinkayo & Demaret, prd, v30, p1846, (1984)"]:
Archive2_ := `besid2-dia`:
