Ndim_ := 4:
x1_ := u:
x2_ := v:
x3_ := w:
x4_ := x:
sig_ := 2:
complex_ := {}:
g11_ := (N(w,x)-L(w,x))*(N(w,x)+L(w,x)):
g12_ := P(w,x)*N(w,x)-M(w,x)*L(w,x):
g22_ := (P(w,x)-M(w,x))*(P(w,x)+M(w,x)):
g33_ := R(w,x)^2:
g44_ := S(w,x)^2:
constraint_ := [ ]:
Info_ := `Simplified Debever McLenaghan Tariq metric`:
Ref_ := ["Debever, grg, v10, p853, (1979)"]:
