Ndim_ := 4:
x1_ := t:
x2_ := x:
x3_ := y:
x4_ := z:
sig_ := 2:
complex_ := {}:
g11_ := -(k*x+d)^(2*m):
g22_ := (k*x+d)^(2*m):
g33_ := (k*x+d)^(2*m):
g44_ := (k*x+d)^(2*m):
constraint_ := [ ]:
Info_ := `Beckers & Sinzinkayo & Demaret`:
Ref_ := ["Beckers & Sinzinkayo & Demaret, prd, v30, p1846, (1984)"]:
Archive2_ := `besid1-dia`:
