Ndim_ := 4:
x1_ := t:
x2_ := phi:
x3_ := rho:
x4_ := z:
sig_ := 2:
complex_ := {}:
g11_ := -rho^(2*m^2)*b^2*cosh(log(a*rho^m))^2:
g22_ := rho^2*b^2*cosh(log(a*rho^m))^2:
g33_ := rho^(2*m^2)*b^2*cosh(log(a*rho^m))^2:
g44_ := 1/b^2/cosh(log(a*rho^m))^2:
constraint_ := [ ]:
Info_ := `Static cylindrically symmetric Einstein-Maxwell field (i) angular magnetic field (caused by an axial current)`:
Archive1_ := `(20.9a) p221`:
