Ndim_ := 4:
x1_ := t:
x2_ := chi:
x3_ := theta:
x4_ := phi:
sig_ := 2:
g11_ := -1:
g22_ := alpha^2*cosh(t/alpha)^2:
g33_ := alpha^2*cosh(t/alpha)^2*sin(chi)^2:
g44_ := alpha^2*cosh(t/alpha)^2*sin(chi)^2*sin(theta)^2:
constraint_ := [ ]:
Info_ := `de Sitter space`:
Archive3_ := `p125`:
