Ndim_ := 4:
x1_ := t:
x2_ := phi:
x3_ := r:
x4_ := z:
sig_ := 2:
complex_ := {}:
g11_ := -r^(2*a)*exp(2*z):
g22_ := r^(2*(1-a))/exp(2*z):
g33_ := r^(2*a*(a-1))*exp(2*(2*a*z-z-r^2/2+C)):
g44_ := r^(2*a*(a-1))*exp(2*(2*a*z-z-r^2/2+C)):
constraint_ := [ ]:
Info_ := `A vacuum metric admitting a nontrivial homothety which is non-null and not hypersurface-orthogonal and whose homothetic bivector is null`:
Ref_ := ["Godfrey, grg, v3, p3, (1972)", "McIntosh, grg, v7, pp199-213, (1976)"]:
