Ndim_ := 4:
x1_ := t:
x2_ := r:
x3_ := theta:
x4_ := phi:
sig_ := 2:
complex_ := {}:
g11_ := -sqrt(7*p0)*r:
g22_ := 7/4:
g33_ := r^2:
g44_ := r^2*sin(theta)^2:
constraint_ := [ ]:
Info_ := `Klein s static spherically symmetric radiation perfect fluid solution`:
Ref_ := ["Klein, afma, v34, pp1-11, (1947)"]:
