Ndim_ := 4:
x1_ := r:
x2_ := theta:
x3_ := phi:
x4_ := t:
sig_ := 2:
complex_ := {}:
g11_ := 1:
g22_ := r^2:
g33_ := r^2*sin(theta)^2:
g44_ := -1:
constraint_ := [ ]:
Info_ := `Minkowski space in polar coordinates`:
