Ndim_ := 4:
x1_ := t:
x2_ := r:
x3_ := theta:
x4_ := phi:
sig_ := 2:
complex_ := {}:
g11_ := -exp(2*nu(r)):
g22_ := exp(2*lambda(r)):
g33_ := r^2:
g44_ := r^2*sin(theta)^2:
constraint_ := [ ]:
Info_ := `The general static, spherically symmetric metric in curvature coordinates`:
Archive1_ := `(14.1) p163`:
