Ndim_ := 4:
x1_ := t:
x2_ := x:
x3_ := y:
x4_ := z:
sig_ := 2:
complex_ := {}:
g11_ := -x^6:
g22_ := x^4*cos(2*t)^2:
g33_ := x^2/cos(2*t):
g44_ := x^2/cos(2*t):
constraint_ := [ ]:
Info_ := `A special stiff perfect fluid case of the Szekeres solution`:
Ref_ := ["Szekeres, cmp, v41, p55, (1975)", "Goode & Wainwright"]:
