#!/bin/bash
# l2h latex to HTML script to call TtH.
if [ $# -lt 1 ] ; then
       echo " Usage: l2h file [switches]" 1>&2
       exit 1
else 
	FILE=$1
	shift 1
	tth <$FILE.tex >$FILE.html -L$FILE $* 
fi